---
- name: Install Nginx and deploy sample HTML page
  hosts: all
  become: yes

  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: latest

  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Deploy a custom index.html
    copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome to Nginx</title></head>
          <body>
          <h1>Nginx is successfully installed!</h1>
          <p>Server: {{ inventory_hostname }}</p>
          </body>
          </html>

  - name: Allow HTTP traffic through UFW
    ufw:
        rule: allow
        name: 'Nginx HTTP'

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted